### ISSUE TITLE
20230920 Feedback

### ISSUE THREAD

**Issue by MisooKim2** [haegun2/CPP202309#2]
challenge/week3/integerFor	no file
위 파일이 없습니다. 파일 명을 확인해주세요.

	challenge/week3/math	no enough comments
위 파일에 코멘트가 부족합니다.

**Comment by MisooKim2** [comment]
(어떻게 해결했는지 작성)
예: math 파일에 주석을 추가하였음

**Comment by haegun2** [comment]
파일명 및 코멘트 수정했습니다 !!
