### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [haegun2/CPP202309#3]
### 없는 파일
- challenge/week2/temperature.cpp
- challenge/week2/temperature2.cpp
	- 위 파일 이름이나 위치를 다시 확인하세요. 해당 소스 파일 채점이 수행되지 않습니다.

### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week3/countChar
    - Warning: multi-character character constant [line 34]
    - Warning: result of comparison of constant 6168666 with expression of type 'char' is always false [line 34]
       - ' ' (작은따옴표) 는 문자를 받기 위한 것인데, 문자 집합인 문자열이 들어가서 에러가 발생했습니다. 
       - 사실 해당 라인의 조건문 블록은 필요 없습니다.제거하세요.

기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in challenge/week2/candy

**Comment by haegun2** [comment]
해당 워닝 내용 수정 후 커밋 완료입니다. challenge 의 경우 해당 수업시간 내 제가 마무리 하지 못하여 미 포함된 파일이었습니다.
